# Generated by Django 6.0.7 on 2026-07-22 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('parent', 'Parent'), ('student', 'Student'), ('alumni', 'Alumni'), ('teacher', 'Teacher')], max_length=20)),
                ('role_detail', models.CharField(blank=True, help_text="Optional extra context, e.g. 'Parent of Grade 5 student', 'Class of 2020'", max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating out of 5 stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('message', models.TextField()),
                ('is_featured', models.BooleanField(default=False, help_text='Featured testimonials appear in the homepage preview section.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive testimonials are hidden from the site without deleting them.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
