# Generated by Django 6.0.7 on 2026-07-22 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('academic', 'Academic Support'), ('extra_curricular', 'Extra Curricular'), ('transportation', 'Transportation'), ('hostel', 'Hostel'), ('library', 'Library'), ('laboratory', 'Laboratories'), ('computer_lab', 'Computer Lab'), ('sports', 'Sports'), ('counselling', 'Counselling'), ('digital_learning', 'Digital Learning')], max_length=30)),
                ('short_description', models.CharField(max_length=255)),
                ('full_description', models.TextField()),
                ('icon_class', models.CharField(blank=True, max_length=50)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='services/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='services.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
