# Generated by Django 6.0.7 on 2026-07-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_name', models.CharField(default='River Queens School', max_length=200)),
                ('tagline', models.CharField(blank=True, help_text="Short phrase shown near the logo, e.g. 'Nurturing Minds, Shaping Futures'.", max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_primary', models.CharField(blank=True, max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('google_maps_embed_url', models.URLField(blank=True)),
                ('office_hours', models.CharField(blank=True, help_text="e.g. 'Sunday - Friday: 9:00 AM - 4:00 PM'", max_length=255)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
