# Generated by Django 6.0.7 on 2026-07-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="Main headline, e.g. 'Nurturing Tomorrow's Leaders Today'", max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Supporting line under the headline.', max_length=300)),
                ('background_image', models.ImageField(upload_to='hero/')),
                ('primary_cta_text', models.CharField(default='Apply for Admission', max_length=50)),
                ('primary_cta_link', models.CharField(default='/admissions/', max_length=255)),
                ('secondary_cta_text', models.CharField(blank=True, default='Contact Us', max_length=50)),
                ('secondary_cta_link', models.CharField(blank=True, default='/contact/', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(blank=True, help_text="Icon identifier used by the template, e.g. 'icon-book-open'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PrincipalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_name', models.CharField(max_length=150)),
                ('designation', models.CharField(default='Principal', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/principal/')),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text='Only one active message is shown at a time.')),
            ],
            options={
                'verbose_name': "Principal's Message",
                'verbose_name_plural': "Principal's Messages",
            },
        ),
        migrations.CreateModel(
            name='StatCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(help_text='e.g. 15, 1200, 98')),
                ('suffix', models.CharField(blank=True, help_text="e.g. '+', '%'", max_length=10)),
                ('label', models.CharField(help_text="e.g. 'Years of Excellence'", max_length=100)),
                ('icon_class', models.CharField(blank=True, help_text="Optional icon identifier used by the template, e.g. 'icon-graduation-cap'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
